### ISSUE TITLE
Verify Logging

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/gamesvr-csgo#1]
@JustinBenedick:

## Does this stock server create and use log files?

Determine if the stock (as in *zero* config changes) version of this server creates log files. If this image doesn't create log files you may have to do this testing on a stock server outside of Docker.

### If no

comment that it doesn't close this issue and skip remaining steps.

### If yes

Let me know (via comments on this issue): 
- if this docker image properly creates / use the log files.
  - if it doesn't @dudleycodes will fix the issue
- the directory (full path) log files are created in.
- the default naming scheme of the log file
  - so that @dudleycodes can create tests that checks for creation/usage of log files.

**Comment by JustinBenedick** [comment]
Log files are confirmed and are working. Tested on csgo tourney image
CSGOTourn99A_Su17h57m26s/csgo/addons/sourcemod/logs
accelerator.log
errors_20180520.log
L20180520.log
STEAMID_20_May_2018.txt


CSGOTourn99A_Su17h57m26s/csgo/logs
_2018-05-20-2300-6987-de_cache.dem
_2018-05-20-2300-6987-de_cache.log
L000_000_000_000_0_201805202257_000.log
L172_030_014_055_27015_201805202257_000.log
